### ISSUE TITLE
Feature: Add test-begin/end lines to the logs

### ISSUE THREAD

**Issue by motty-stratoscale** [Stratoscale/docker-test-tools#24]
Since the runner can run many tests consecutively, it can be hard to trace the logs of a specific test.
So you may like to append a line like "==== Test [name] beginning/ending ====" to all the logs, on the setUp & tearDown of each test.

**Comment by lior-stratoscale** [comment]
+1

**Comment by shay-stratoscale** [comment]
supported since 1.0.5
